### ISSUE TITLE
Sudden cooldown reductions

### ISSUE THREAD

**Issue by chullie07** [Darkon47/RPGMods#13]
Issue: Sudden massive cooldown reduction is applied to players after unequipping gear and reequipping. Having no equipped gear sets cooldowns back to normal. Having gear equipped massively reduces cooldown, sometimes to the point of having no cooldown at all for some skills. 

Previously had installed v1.7.2 then updated to v1.7.4

Steps to replicate:
1. Verify cooldown timers are normal
2. Unequip all gear including weapon
3. Use a skill
4. Re-equip all gear and weapon
5. Use a skill

Expected result: No change in cooldown timers between steps 3-5

Actual result: Significant cooldown reduction at step 5 compared to step 3

Other notes: 
- Experience system disabled
- Gear Level is enabled
- Mastery CDR stacks is enabled
- nocooldown chat command is not related. Bug is applied to admin and non-admin alike
- nocooldown permissions set to 100/admin
- server is hosted by valhost.net

**Comment by Darkon47** [comment]
1.7.4 had some issues as that was in a period where i wasnt testing due to work, and was reliant on other peoples reports, this should be fully resolved right now, please reopen if it is an issue on recent versions.
