### ISSUE TITLE
alot of command not work

### ISSUE THREAD

**Issue by cielthephantom2** [Darkon47/RPGMods#9]
i only can use some command that this play when type .help , other like myinfo , playerinfo ..etc not working

**Comment by cojo1989** [comment]
Yep, I have same issue, I was using the plugin only for the commands to be fair... sadly they are not working anymore. Maybe developer will have a change of heart and fix them :)

**Comment by Darkon47** [comment]
A lot of these are moved to community commands, others are just not in scope for the current state of RPGMods, someone asked permission to split off the pvp content, so i havent worked on that.
